// Export & Reporting
import type { IncidentCase, ExportArtifact } from '../schemas';
import { v4 as uuid } from 'uuid';

export function generateIncidentReport(c: IncidentCase): string {
  const a = c.assessment;
  const p = c.actionPlan;

  let report = `# INCIDENT REPORT\n\n`;
  report += `**Title:** ${c.title}\n`;
  report += `**Status:** ${c.status.toUpperCase()}\n`;
  report += `**Severity:** ${(a?.severity || c.severity).toUpperCase()}\n`;
  report += `**Category:** ${(a?.category || c.category).toUpperCase()}\n`;
  report += `**Reported:** ${new Date(c.reportedAt).toLocaleString()}\n`;
  report += `**Last Updated:** ${new Date(c.updatedAt).toLocaleString()}\n\n`;

  if (c.location) report += `**Location:** ${c.location}\n\n`;

  if (a) {
    report += `## ASSESSMENT\n\n`;
    report += `${a.summary}\n\n`;
    report += `**Key Hazards:** ${a.keyHazards.join(', ') || 'None identified'}\n`;
    report += `**Affected People:** ${a.affectedPeople}\n`;
    report += `**Affected Assets:** ${a.affectedAssets}\n`;
    report += `**Time Sensitivity:** ${a.timeSensitivity}\n\n`;
  }

  if (p) {
    report += `## IMMEDIATE PRIORITIES\n\n`;
    p.immediatePriorities.forEach((item) => {
      report += `- [ ] [${item.priority.toUpperCase()}] ${item.text}\n`;
    });

    report += `\n## NEXT STEPS\n\n`;
    p.nextSteps.forEach((item) => {
      report += `- [ ] [${item.priority.toUpperCase()}] ${item.text}\n`;
    });

    report += `\n## REQUIRED EQUIPMENT\n\n`;
    p.requiredEquipment.forEach((eq) => {
      report += `- ${eq}\n`;
    });

    report += `\n## SAFETY WARNINGS\n\n`;
    p.safetyWarnings.forEach((w) => {
      report += `- **${w.severity.toUpperCase()}:** ${w.warning}\n`;
    });

    report += `\n## ESCALATION\n\n${p.escalationGuidance}\n`;
    report += `\n## HANDOFF SUMMARY\n\n${p.handoffSummary}\n`;
  }

  if (a?.missingInformation && a.missingInformation.length > 0) {
    report += `\n## MISSING INFORMATION\n\n`;
    a.missingInformation.forEach((m) => {
      report += `- ${m}\n`;
    });
  }

  report += `\n---\n*Generated by RescueMesh — Edge AI Field Copilot*\n`;
  report += `*All processing performed on-device. No cloud services used.*\n`;

  return report;
}

export function generateActionChecklistReport(c: IncidentCase): string {
  const p = c.actionPlan;
  if (!p) return 'No action plan generated yet.';

  let report = `# ACTION CHECKLIST — ${c.title}\n\n`;
  report += `**Severity:** ${c.assessment?.severity?.toUpperCase() || 'UNKNOWN'}\n`;
  report += `**Generated:** ${new Date(p.generatedAt).toLocaleString()}\n\n`;

  report += `## ⚡ IMMEDIATE PRIORITIES\n\n`;
  p.immediatePriorities.forEach((item) => {
    report += `- [${item.completed ? 'x' : ' '}] [${item.priority.toUpperCase()}] ${item.text}\n`;
  });

  report += `\n## 📋 NEXT STEPS\n\n`;
  p.nextSteps.forEach((item) => {
    report += `- [${item.completed ? 'x' : ' '}] [${item.priority.toUpperCase()}] ${item.text}\n`;
  });

  report += `\n## ⚠️ SAFETY WARNINGS\n\n`;
  p.safetyWarnings.forEach((w) => {
    report += `- **${w.severity.toUpperCase()}:** ${w.warning}\n`;
  });

  return report;
}

export function generateHandoffNote(c: IncidentCase): string {
  const a = c.assessment;
  const p = c.actionPlan;

  let note = `# HANDOFF NOTE — ${c.title}\n\n`;
  note += `**Severity:** ${(a?.severity || c.severity).toUpperCase()}\n`;
  note += `**Category:** ${(a?.category || c.category).toUpperCase()}\n\n`;

  if (p?.handoffSummary) {
    note += `${p.handoffSummary}\n\n`;
  }

  if (a?.keyHazards && a.keyHazards.length > 0) {
    note += `**Key Hazards:** ${a.keyHazards.join('; ')}\n`;
  }

  note += `\n---\n*Handed off via RescueMesh — Edge AI Field Copilot*\n`;
  return note;
}

export function createExportArtifact(
  caseId: string,
  type: ExportArtifact['type'],
  content: string,
  format: ExportArtifact['format'] = 'markdown'
): ExportArtifact {
  return {
    id: uuid(),
    caseId,
    type,
    content,
    format,
    createdAt: new Date().toISOString(),
  };
}
